#!/bin/sh
set -e
shopt -s nullglob

files() {
	for glob in $(
	make -pn |
		grep -E '^[^.][a-zA-Z/%.]*:' |
		sed 's/^.*://' |
		tr ' %' '\n*' |
		sort |
		uniq
	)
	do
		case "$glob" in
			*\**)
				echo $glob
				;;
			*)
				if [[ -e $glob ]]
				then
					echo $glob
				fi
				;;
		esac
	done
}

while :
do
	inotifywait --format "%e %f" -e close_write,create,modify,delete $(files) || true
	time make
done
